server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

spring:
  application:
    name: EUREKA-SERVER
  boot:
    admin:
      client:
        url: http://localhost:9091
        enabled: true
        auto-registration: true
        instance:
          name: ${spring.application.name:JSS}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO