global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'Spring Boot Application'
    metrics_path: '/management/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'GAS-PLANT-SERVICE'

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

